#! /bin/bash

lex src/dico.lex
#yacc src/grammaire.yacc

#mv y.tab.c grammaire.c
mv lex.yy.c dico.c

gcc -o bin/dico.exe dico.c -lfl

#gcc grammaire.c -ly -ll

#mv a.out bin/traducteur.exe

#rm dico.c grammaire.c
rm dico.c
